name: 'Close PR'
description: 'Close PR if duplicated and already approved'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'